services:
  app:
    build: .
    ports:
      - "1212:1212"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/db_doc
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    networks:
      - springnet

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_DATABASE: db_doc
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springnet

volumes:
  mysql_data:

networks:
  springnet:
